// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/posts.proto

package posts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SaveRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug                 string   `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tags                 []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e93dc7d934d9dc10, []int{0}
}

func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (m *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(m, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SaveRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SaveRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *SaveRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SaveRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SaveRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type SaveResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e93dc7d934d9dc10, []int{1}
}

func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (m *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(m, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

func (m *SaveResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Post struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug                 string   `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Created              int64    `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,6,opt,name=updated,proto3" json:"updated,omitempty"`
	Author               string   `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"`
	Tags                 []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_e93dc7d934d9dc10, []int{2}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Post) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *Post) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Post) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*SaveRequest)(nil), "posts.SaveRequest")
	proto.RegisterType((*SaveResponse)(nil), "posts.SaveResponse")
	proto.RegisterType((*Post)(nil), "posts.Post")
}

func init() {
	proto.RegisterFile("proto/posts.proto", fileDescriptor_e93dc7d934d9dc10)
}

var fileDescriptor_e93dc7d934d9dc10 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x51, 0xdb, 0x4a, 0xc3, 0x40,
	0x10, 0x35, 0xcd, 0xa5, 0x76, 0x14, 0xc1, 0x51, 0x64, 0x11, 0x91, 0x92, 0x27, 0x9f, 0x2a, 0xea,
	0x9b, 0x5f, 0x21, 0xf1, 0x0b, 0x56, 0x33, 0xd4, 0x40, 0x9b, 0x5d, 0x33, 0x13, 0x7f, 0xc4, 0xbf,
	0xf1, 0xeb, 0xcc, 0xce, 0xa6, 0x46, 0x7d, 0xef, 0xdb, 0xb9, 0xc0, 0xe1, 0xcc, 0x1c, 0x38, 0xf5,
	0x9d, 0x13, 0x77, 0xeb, 0x1d, 0x0b, 0xaf, 0x14, 0x63, 0xae, 0xa4, 0xfc, 0x4c, 0xe0, 0xe8, 0xd9,
	0x7e, 0x50, 0x45, 0xef, 0x3d, 0xb1, 0xe0, 0x09, 0xcc, 0x9a, 0xda, 0x24, 0xcb, 0xe4, 0x66, 0x51,
	0x0d, 0x08, 0xcf, 0x21, 0x97, 0x46, 0x36, 0x64, 0x66, 0x2a, 0x45, 0x82, 0x08, 0x19, 0x6f, 0xfa,
	0xb5, 0x49, 0x55, 0x54, 0x8c, 0x06, 0xe6, 0xaf, 0xae, 0x15, 0x6a, 0xc5, 0x64, 0x2a, 0xef, 0x28,
	0x5e, 0xc1, 0x42, 0x9a, 0xed, 0x90, 0x6e, 0xb7, 0xde, 0xe4, 0x83, 0x97, 0x56, 0x93, 0x10, 0xb2,
	0xc4, 0xae, 0xd9, 0x14, 0xcb, 0x34, 0x64, 0x05, 0x5c, 0x5e, 0xc3, 0x71, 0x2c, 0xc5, 0xde, 0xb5,
	0x4c, 0xff, 0x5b, 0x95, 0x5f, 0x09, 0x64, 0x4f, 0x6e, 0x4f, 0x75, 0x83, 0xd3, 0x91, 0x15, 0xaa,
	0xc7, 0xb2, 0x3b, 0x1a, 0x9c, 0xde, 0xd7, 0xea, 0x14, 0xd1, 0x19, 0x29, 0x5e, 0x40, 0x61, 0x7b,
	0x79, 0x73, 0x9d, 0x99, 0x6b, 0xd8, 0xc8, 0x7e, 0x8e, 0x3b, 0x9c, 0x8e, 0xbb, 0x7f, 0x84, 0x3c,
	0x74, 0x67, 0xbc, 0x83, 0x2c, 0x5c, 0x89, 0xb8, 0x8a, 0xc3, 0xfc, 0xda, 0xe1, 0xf2, 0xec, 0x8f,
	0x16, 0xdf, 0x50, 0x1e, 0xbc, 0x14, 0x3a, 0xde, 0xc3, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd1,
	0xc6, 0xfb, 0x71, 0xd1, 0x01, 0x00, 0x00,
}
